name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Vet
      run: make vet
    - name: Test
      run: make test
    - name: Website test
      run: make website-test
